export const eventData = [
    {
      id: 1,
      title: "React Conf 2025",
      text: "Latest insights in React. Learn about new hooks, server components, and more.",
      date: "June 25",
      time: "10:00 AM",
      location: "Moscone Center, San Francisco, California, USA",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNdi6Gavxh_hhmb3SY4wDfn-mvdtPkvMvKKA&s",
    },
    {
      id: 2,
      title: "JS World Summit",
      text: "Global JS dev summit.",
      date: "July 12",
      time: "9:00 AM",
      location: "Berlin",
      image: "https://img.freepik.com/free-vector/modern-music-event-poster-template_1361-1292.jpg?semt=ais_hybrid&w=740",
    },
    {
      id: 3,
      title: "Tech Expo 2025",
      text: "Tech breakthroughs showcase.",
      date: "Aug 5",
      time: "1:00 PM",
      location: "Tokyo",
      image: "https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg",
    },
    {
      id: 1,
      title: "React Conf 2025",
      text: "Latest insights in React.",
      date: "June 25",
      time: "10:00 AM",
      location: "San Francisco",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNdi6Gavxh_hhmb3SY4wDfn-mvdtPkvMvKKA&s",
    },
    {
      id: 2,
      title: "JS World Summit",
      text: "Global JS dev summit. At Our location Free Pizza",
      date: "July 12",
      time: "9:00 AM",
      location: "Berlin",
      image: "https://img.freepik.com/free-vector/modern-music-event-poster-template_1361-1292.jpg?semt=ais_hybrid&w=740",
    },
    {
      id: 3,
      title: "Tech Expo 2025",
      text: "Tech breakthroughs showcase.",
      date: "Aug 5",
      time: "1:00 PM",
      location: "Tokyo",
      image: "https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg",
    },
    {
      id: 1,
      title: "React Conf 2025",
      text: "Latest insights in React.",
      date: "June 25",
      time: "10:00 AM",
      location: "San Francisco",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNdi6Gavxh_hhmb3SY4wDfn-mvdtPkvMvKKA&s",
    },
    {
      id: 2,
      title: "JS World Summit",
      text: "Global JS dev summit.",
      date: "July 12",
      time: "9:00 AM",
      location: "Berlin",
      image: "https://img.freepik.com/free-vector/modern-music-event-poster-template_1361-1292.jpg?semt=ais_hybrid&w=740",
    },
    {
      id: 3,
      title: "Tech Expo 2025",
      text: "Tech breakthroughs showcase.",
      date: "Aug 5",
      time: "1:00 PM",
      location: "Tokyo",
      image: "https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg",
    },
    {
      id: 3,
      title: "Tech Expo 2025",
      text: "Tech breakthroughs showcase.",
      date: "Aug 5",
      time: "1:00 PM",
      location: "Tokyo",
      image: "https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg",
    },
    {
      id: 3,
      title: "Tech Expo 2025",
      text: "Tech breakthroughs showcase.",
      date: "Aug 5",
      time: "1:00 PM",
      location: "Tokyo",
      image: "https://static.vecteezy.com/system/resources/thumbnails/041/388/388/small/ai-generated-concert-crowd-enjoying-live-music-event-photo.jpg",
    },
  ];