
export type VideoItem = {
    id: string;
    thumbnail: string;
    video: string;
    fullVideo: string;
    title: string;
    description: string;
    rating: number;
    date: string;
    plot: string;
    genre: string[];      
    language: string;
    duration: string;
    cast: string[];      
    director: string;
    type: "Movie" | "Show" | "Documentary" | "News" | "Classic" | "Historical" | "Sci-Fi" | "Thriller" | "Superhero" | "AD" | "Cartoon"; 
  };

export const CartoonMovies : VideoItem[] =[
  {
    "id": "GULL-1939",
    "title": "Gulliver's Travels",
    "description": "Gulliver's Travels 1939 movie trailer",
    "thumbnail": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/gullivers_travels/500px-Gulliverstravelsopening1939.jpeg",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/gullivers_travels/gullivers_travels1939_512kb.mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/gullivers_travels/gullivers_travels1939_512kb.mp4",
    "rating": 4.0,
    "date": "1939",
    "plot": "A musical animated adventure following the travels of Lemuel Gulliver as he encounters strange societies and fantastical creatures.",
    "genre": ["Animation", "Adventure", "Family"],
    "language": "English",
    "duration": "1h 19m",
    "cast": ["Sam Parker", "Lanny Ross", "Alfred Hawkins"],
    "director": "Dave Fleischer",
    "type": "Cartoon"
  },
  {
    "id": "ELIO-2023",
    "title": "Elio",
    "description": "Official Trailer - Pixar",
    "thumbnail": "https://i0.wp.com/atthemoviesonline.com/wp-content/uploads/2023/06/MV5BZDhkMTU1ZjYtNzFiOS00N2U5LTg2M2QtZmMxMTFhZmJmZGY5XkEyXkFqcGdeQXVyMTE0MzQwMjgz._V1_.jpg?fit=1400%2C700&ssl=1",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/Elio/Elio%20%20Official%20Trailer%20-%20Pixar%20(720p%2C%20h264).mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/Elio/Elio%20%20Official%20Trailer%20-%20Pixar%20(720p%2C%20h264).mp4",
    "rating": 4.5,
    "date": "2023",
    "plot": "A young boy discovers he has an alien heritage and embarks on an intergalactic adventure that will change the course of history.",
    "genre": ["Animation", "Adventure", "Sci-Fi"],
    "language": "English",
    "duration": "1h 42m",
    "cast": ["Voice: Jacob Tremblay", "Voice: Jameela Jamil"],
    "director": "Adrian Molina",
    "type": "Cartoon"
  },
  {
    id: "gymAds-001",
    title: "Gym Ad",
    description: "An ad for a fitness gym offering special discounts for new memberships.",
    thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.png",
    video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.mp4",
    fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.mp4",
    rating: 4,
    date: "n/a",
    plot: "n/a",
    genre: ["n/a"],
    language: "n/a",
    duration: "n/a",
    cast: ["n/a"],
    director: "n/a",
    type: "AD"
  },
  {
    "id": "DRAGON-2010",
    "title": "How To Train Your Dragon",
    "description": "Official Trailer - Universal Pictures",
    "thumbnail": "https://images.squarespace-cdn.com/content/v1/54400c3de4b06a018e97259e/df065393-55e9-4145-b07a-3c93ab9b81ea/AAAABYuoBJ8JQWVPnv7rmbLLfRZoIigxFxqz2JlHIpQkdU_tN31tzZ3cYu8uYkwOk5_6Bjklz2HkvGx_PqOPQTc7LJqkyhSb.jpg",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/How%20To%20Train%20Your%20Dragon/How%20To%20Train%20Your%20Dragon%20%20Official%20Trailer%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/How%20To%20Train%20Your%20Dragon/How%20To%20Train%20Your%20Dragon%20%20Official%20Trailer%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
    "rating": 4.8,
    "date": "2010",
    "plot": "A young Viking befriends a dragon, changing the future of his village and discovering a new way of life.",
    "genre": ["Animation", "Adventure", "Family"],
    "language": "English",
    "duration": "1h 38m",
    "cast": ["Jay Baruchel", "Gerard Butler", "America Ferrera"],
    "director": "Chris Sanders",
    "type": "Cartoon"
  },
  {
    "id": "MOANA-2023",
    "title": "Moana 2",
    "description": "Official Trailer - Walt Disney Animation Studios",
    "thumbnail": "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/E7969CDB6F7D30CE05984DC8D31429B38267AAD1C2B16B1545E6976B49F95120/scale?width=1200&aspectRatio=1.78&format=webp",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/Moana2/Moana%202%20%20Official%20Trailer%20-%20Walt%20Disney%20Animation%20Studios%20(720p%2C%20h264).mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/Moana2/Moana%202%20%20Official%20Trailer%20-%20Walt%20Disney%20Animation%20Studios%20(720p%2C%20h264).mp4",
    "rating": 4.6,
    "date": "2023",
    "plot": "Moana returns to the sea for another adventure, this time to save her island from an impending danger.",
    "genre": ["Animation", "Adventure", "Family"],
    "language": "English",
    "duration": "1h 45m",
    "cast": ["Auli'i Cravalho", "Dwayne Johnson"],
    "director": "John Musker",
    "type": "Cartoon"
  },
  {
    "id": "BADGUYS-2022",
    "title": "The Bad Guys",
    "description": "Official Trailer 1 - Universal Pictures",
    "thumbnail": "https://occ-0-8407-90.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABcNTrI7fcrdBwxPMixjSzabQZL3qPbPxsHp1YjvNKzIAKmYN979yymTUs3W_mzwEifdU0_J0bmvTnL7E2Gfbdi17NSHJpiRwEUV2.jpg?r=639",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Bad%20Guys/THE%20BAD%20GUYS%20%20Official%20Trailer%201%20-%20Universal%20Pictures%20(1080p%2C%20h264).mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Bad%20Guys/THE%20BAD%20GUYS%20%20Official%20Trailer%201%20-%20Universal%20Pictures%20(1080p%2C%20h264).mp4",
    "rating": 4.2,
    "date": "2022",
    "plot": "A group of reformed criminals embark on an adventure to save the world from an evil villain.",
    "genre": ["Animation", "Action", "Comedy"],
    "language": "English",
    "duration": "1h 40m",
    "cast": ["Sam Rockwell", "Awkwafina", "Marc Maron"],
    "director": "Pierre Perifel",
    "type": "Cartoon"
  },
  {
    id: "hairAds-001",
    title: "Hair Products Ad",
    description: "An ad for a hair care product that promises to give you healthy, shiny hair.",
    thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.png",
    video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.mp4",
    fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.mp4",
    rating: 5,
    date: "n/a",
    plot: "n/a",
    genre: ["n/a"],
    language: "n/a",
    duration: "n/a",
    cast: ["n/a"],
    director: "n/a",
    type: "AD"
  },
  {
    "id": "WILDROBOT-2023",
    "title": "The Wild Robot",
    "description": "Official Trailer - Universal Pictures",
    "thumbnail": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv-1CT1BhqMy3kvNVV2aTRas0wNMz51UYwAg&s",
    "video": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Wild%20Robot/The%20Wild%20Robot%20%20Official%20Trailer%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
    "fullVideo": "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Wild%20Robot/The%20Wild%20Robot%20%20Official%20Trailer%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
    "rating": 4.4,
    "date": "2023",
    "plot": "A robot, stranded on a remote island, learns to adapt and form bonds with the local wildlife.",
    "genre": ["Animation", "Adventure", "Family"],
    "language": "English",
    "duration": "1h 38m",
    "cast": ["Voice: Jessica Chastain", "Voice: Jeffrey Wright"],
    "director": "Chris Wedge",
    "type": "Cartoon"
  }
]

  
export const ActionMovies : VideoItem[] = [
  {
    id: "barAds-001",
    title: "Bar Ad",
    description: "A promotional ad for a trendy bar, showcasing its ambiance and drinks.",
    thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.png",
    video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.mp4",
    fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.mp4",
    rating: 4.8,
    date: "n/a",
    plot: "n/a",
    genre: ["n/a"],
    language: "n/a",
    duration: "n/a",
    cast: ["n/a"],
    director: "n/a",
    type: "AD"
  },
    {
      id: "civilWar-001",
      title: "Civil War Official Trailer",
      description: "The official trailer for the Civil War movie, a gripping story that delves into the epic battles of the American Civil War.",
      thumbnail: "https://i.ytimg.com/vi/aDyQxtg0V2w/maxresdefault.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Civil%20War/Civil%20War",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Civil%20War/Civil%20War",
      rating: 4.5,
      date: "2023",
      plot: "An intense and emotional portrayal of the Civil War, focusing on the individuals who lived through it and the choices they had to make.",
      genre: ["Action", "War", "Drama"],
      language: "English",
      duration: "2h 15m",
      cast: ["John Doe", "Jane Smith"],
      director: "A24",
      type: "Historical"
    },
    {
      id: "mortalEngines-001",
      title: "Mortal Engines Official Trailer",
      description: "The official trailer for Mortal Engines, a post-apocalyptic adventure where cities move on massive wheels and battle each other for survival.",
      thumbnail: "https://i.ytimg.com/vi/IRsFc2gguEg/sddefault.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Mortal%20Engines/Mortal%20Engines%20-%20Official%20Trailer%20(HD)%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Mortal%20Engines/Mortal%20Engines%20-%20Official%20Trailer%20(HD)%20-%20Universal%20Pictures%20(720p%2C%20h264).mp4",
      rating: 4.0,
      date: "2018",
      plot: "A thrilling adventure set in a futuristic world where cities roam the earth, devouring each other in a desperate fight for resources.",
      genre: ["Action", "Adventure", "Sci-Fi"],
      language: "English",
      duration: "2h 9m",
      cast: ["Hera Hilmar", "Robert Sheehan"],
      director: "Christian Rivers",
      type: "Sci-Fi"
    },
    {
      id: "predatorBadlands-001",
      title: "Predator Badlands Teaser Trailer",
      description: "A teaser trailer for Predator: Badlands, the latest installment in the iconic Predator franchise, set in the hostile badlands.",
      thumbnail: "https://i.ytimg.com/vi/15wupYlLAGM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBxS9iwXOlhOXDG6WwjOxmT6dc21Q",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Predator%20Badlands/Predator%20Badlands%20%20Teaser%20Trailer%20-%2020th%20Century%20Studios%20(1080p%2C%20h264).mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Predator%20Badlands/Predator%20Badlands%20%20Teaser%20Trailer%20-%2020th%20Century%20Studios%20(1080p%2C%20h264).mp4",
      rating: 4.3,
      date: "2022",
      plot: "A Predator arrives in a desolate, dangerous wasteland, where a group of survivors must fight for their lives.",
      genre: ["Action", "Sci-Fi", "Thriller"],
      language: "English",
      duration: "2m 30s",
      cast: ["Amber Midthunder", "Dan Trachtenberg"],
      director: "Dan Trachtenberg",
      type: "Thriller"
    },
    {
      id: "thunderbolts-001",
      title: "Thunderbolts Official Trailer",
      description: "Marvel Studios' Thunderbolts trailer, introducing a new group of heroes and antiheroes tasked with saving the world.",
      thumbnail: "https://i.ytimg.com/vi/ccgGSrXhUFc/maxresdefault.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Thunderbolts/Marvel%20Studios'%20Thunderbolts%20%20Official%20Trailer%20%20In%20Cinemas%20May%201%20-%20IndiaMarvel%20(1080p%2C%20h264).mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/Thunderbolts/Marvel%20Studios'%20Thunderbolts%20%20Official%20Trailer%20%20In%20Cinemas%20May%201%20-%20IndiaMarvel%20(1080p%2C%20h264).mp4",
      rating: 4.7,
      date: "2023",
      plot: "Thunderbolts brings together a group of unconventional superheroes and antiheroes as they face a dangerous threat to the world.",
      genre: ["Action", "Adventure", "Superhero"],
      language: "English",
      duration: "2m 20s",
      cast: ["Florence Pugh", "Sebastian Stan"],
      director: "Jake Schreier",
      type: "Superhero"
    },
    {
      id: "cakeAds-001",
      title: "Cake Ad",
      description: "An ad promoting delicious cakes from a local bakery, perfect for all occasions.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.png",
      video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.mp4",
      rating: 4.3,
      date: "n/a",
      plot: "n/a",
      genre: ["n/a"],
      language: "n/a",
      duration: "n/a",
      cast: ["n/a"],
      director: "n/a",
      type: "AD"
    }
  
]


export const ClassicMovies : VideoItem[] = [
    {
      id: "royalW-001",
      title: "Royal Wedding",
      description: "In this classic musical romance, a brother and sister dance duo travel to London during the Royal Wedding of Princess Elizabeth. Amid elegant ballrooms and wartime uncertainties, romance blossoms and the show must go on.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/royal_wedding/500px-Fred_Astaire_and_Jane_Powell_in_Royal_Wedding.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/royal_wedding/royal_wedding_512kb.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/royal_wedding/royal_wedding_512kb.mp4",
      rating: 4.2,
      date: "1951",
      plot: "Fred Astaire and Jane Powell star in this delightful tale of dance, love, and royal celebration, set against the backdrop of the 1947 royal wedding in London.",
      genre: ["Musical", "Romance", "Comedy"],
      language: "English",
      duration: "1h 33m",
      cast: ["Fred Astaire", "Jane Powell"],
      director: "Stanley Donen",
      type: "Classic"
    },
    {
      id: "donutsAds-001",
      title: "Donuts Ad",
      description: "An ad for a donut shop offering a variety of fresh donuts, perfect for your sweet cravings.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donatsAds.png",
      video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donutads.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donutads.mp4",
      rating: 4,
      date: "n/a",
      plot: "n/a",
      genre: ["n/a"],
      language: "n/a",
      duration: "n/a",
      cast: ["n/a"],
      director: "n/a",
      type: "AD"
    },
    {
      id: "johnD-002",
      title: "Meet John Doe",
      description: "A cynical journalist and a down-on-his-luck drifter create a fictional man to criticize society, but the hoax takes on a life of its own in this gripping drama.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/meet_john_doe/Poster_-_Meet_John_Doe_01.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/meet_john_doe/meet_john_doe_512kb.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/meet_john_doe/meet_john_doe_512kb.mp4",
      rating: 4.6,
      date: "1941",
      plot: "Frank Capra’s powerful commentary on media manipulation and the human spirit, featuring a moving performance by Gary Cooper.",
      genre: ["Drama", "Romance"],
      language: "English",
      duration: "2h 3m",
      cast: ["Gary Cooper", "Barbara Stanwyck"],
      director: "Frank Capra",
      type: "Classic"
    },
    {
      id: "littleP-003",
      title: "The Little Princess",
      description: "When her father goes missing in war, a spirited young girl faces hardships at boarding school but never loses hope in this heartfelt classic.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/little_princess/500px-Little_Princess_4.jpeg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/little_princess/little_princess_512kb.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/little_princess/little_princess_512kb.mp4",
      rating: 4.3,
      date: "1939",
      plot: "Shirley Temple stars as a hopeful young girl who refuses to believe her beloved father is lost in battle.",
      genre: ["Drama", "Family"],
      language: "English",
      duration: "1h 33m",
      cast: ["Shirley Temple"],
      director: "Walter Lang",
      type: "Classic"
    },
    {
      id: "friesAds-001",
      title: "Fries Ad",
      description: "A crispy, golden fries ad for a fast-food chain, perfect for your snacking moments.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.png",
      video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.mp4",
      rating: 5,
      date: "n/a",
      plot: "n/a",
      genre: ["n/a"],
      language: "n/a",
      duration: "n/a",
      cast: ["n/a"],
      director: "n/a",
      type: "AD"
    },
    {
      id: "ironM-004",
      title: "The Iron Mask",
      description: "An epic swashbuckling tale of intrigue, brotherhood, and a secret twin. The Musketeers return to defend France in this silent-era classic.",
      thumbnail: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/iron_mask/500px-Ironmaskposter.jpg",
      video: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/iron_mask/iron_mask_512kb.mp4",
      fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/movies/iron_mask/iron_mask_512kb.mp4",
      rating: 4.0,
      date: "1929",
      plot: "Douglas Fairbanks leads a daring tale of adventure and hidden royalty, adapted from the final part of Dumas' Musketeer saga.",
      genre: ["Adventure", "Drama", "History"],
      language: "English (Silent)",
      duration: "1h 35m",
      cast: ["Douglas Fairbanks"],
      director: "Allan Dwan",
      type: "Classic"
    }
            
    
] 


export const videos: VideoItem[] = [
  {
    id: "BADGUYS-2022",
    title: "The Bad Guys",
    description: "Official Trailer 1 - Universal Pictures",
    thumbnail: "https://occ-0-8407-90.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABcNTrI7fcrdBwxPMixjSzabQZL3qPbPxsHp1YjvNKzIAKmYN979yymTUs3W_mzwEifdU0_J0bmvTnL7E2Gfbdi17NSHJpiRwEUV2.jpg?r=639",
    video: "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Bad%20Guys/THE%20BAD%20GUYS%20%20Official%20Trailer%201%20-%20Universal%20Pictures%20(1080p%2C%20h264).mp4",
    fullVideo: "https://storage.googleapis.com/1000gns/1001/content/videos/cartoons/The%20Bad%20Guys/THE%20BAD%20GUYS%20%20Official%20Trailer%201%20-%20Universal%20Pictures%20(1080p%2C%20h264).mp4",
    rating: 4.2,
    date: "2022",
    plot: "A group of reformed criminals embark on an adventure to save the world from an evil villain.",
    genre: ["Animation", "Action", "Comedy"],
    language: "English",
    duration: "1h 40m",
    cast: ["Sam Rockwell", "Awkwafina", "Marc Maron"],
    director: "Pierre Perifel",
    type: "Cartoon"
  },
  {
    id: "restaurantAds-001",
    title: "Restaurant Ad",
    description: "A mouth-watering ad for a local restaurant offering a special discount on meals.",
    thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.png",
    video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.mp4",
    fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.mp4",
    rating: 3,
    date: "n/a",
    plot: "n/a",
    genre: ["n/a"],
    language: "n/a",
    duration: "n/a",
    cast: ["n/a"],
    director: "n/a",
    type: "AD"
  },
    {
      id: "saloN-z6p8",
      title: "Ringing In 2022 With Style",
      description: "After months of careful and detailed planning by a local youth council, a New Year’s Eve Dance was held on Friday night, Dec. 31, for Moapa Valley teens. The dance was held at the Logandale Stake Center of the Church of Jesus Christ of Latter-day Saints. Youth, ages 14 and up, from all over the Moapa Valley communities, gathered at the church to celebrate the final hours of 2021 and spend the beginning of 2022 together.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909262/stream/video/01MainNewsVideo/01MainNewsThumb_z8d3cb.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909623/stream/video/01MainNewsVideo/01MainNewsVideo_online-video-cutter.com_smsmrd.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745908947/stream/video/01MainNewsVideo/01MainNewsVideo_ktjkop.mp4",
      rating: 4.5,
      date: "2020",
      plot: "From ancient waterfalls to hidden river cities, explore how water shaped humanity’s greatest triumphs.",
      genre: ["Documentary", "Travel", "History"],
      language: "English",
      duration: "1h 15m",
      cast: ["Narrated by Oliver Brooks"],
      director: "Isla Cascade",
      type: "Documentary"
    },
    {
      id: "BIRD-a8f3",
      title: "Bird Adventures",
      description: "A stunning story of freedom, nature, and colorful birds soaring across continents.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909290/stream/video/02BirdVideo/02BirdThumb_xmr6ld.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745908977/stream/video/02BirdVideo/02BirdVideo_hprerk.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745908977/stream/video/02BirdVideo/02BirdVideo_hprerk.mp4",
      rating: 4.5,
      date: "2023",
      plot: "Follow the thrilling journey of a brave bird who defies storms, predators, and the unknown in search of its home.",
      genre: ["Adventure", "Nature", "Family"],
      language: "English",
      duration: "1h 45m",
      cast: ["Olivia Feather", "Sky Breeze"],
      director: "James Wildwing",
      type: "Movie"
    },
    {
      id: "CAME-5d2r",
      title: "Camera Girl",
      description: "Through the lens of a dreamer, ordinary life turns extraordinary.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909309/stream/video/03CameraGirlVideo/03CameraGirlThumb_gjucyi.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909006/stream/video/03CameraGirlVideo/03CameraGirlVideo_wd51px.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909006/stream/video/03CameraGirlVideo/03CameraGirlVideo_wd51px.mp4",
      rating: 4.7,
      date: "2022",
      plot: "A young photographer stumbles upon a hidden world invisible to the naked eye, changing her destiny forever.",
      genre: ["Drama", "Mystery"],
      language: "English",
      duration: "2h 10m",
      cast: ["Samantha Lane", "Jordan Vance"],
      director: "Rebecca Storm",
      type: "Movie"
    },
    {
      id: "FISH-p9x7",
      title: "Fish Tales",
      description: "Discover the breathtaking wonders of life beneath the ocean.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909322/stream/video/04FishVideo/04FishThumb_zmr0gm.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909143/stream/video/04FishVideo/04FishVideo_fjvioc.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909143/stream/video/04FishVideo/04FishVideo_fjvioc.mp4",
      rating: 4.3,
      date: "2021",
      plot: "Dive deep into crystal-clear waters and witness the secret lives of the ocean’s most fascinating creatures.",
      genre: ["Documentary", "Nature"],
      language: "English",
      duration: "55m",
      cast: ["Narrated by David Shales"],
      director: "Sophie Waters",
      type: "Documentary"
    },
    {
      id: "FLOW-x3t8",
      title: "Flower Kingdom",
      description: "Step into a magical realm where every petal tells a story.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909350/stream/video/05FlowerVideo/05FlowerThumb_azxpna.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909161/stream/video/05FlowerVideo/05FlowerVideo_rruzqd.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909161/stream/video/05FlowerVideo/05FlowerVideo_rruzqd.mp4",
      rating: 4.6,
      date: "2020",
      plot: "An enchanting journey through fields of vivid color and whispered myths hidden among blooms.",
      genre: ["Fantasy", "Adventure"],
      language: "English",
      duration: "1h 30m",
      cast: ["Lily Bloom", "Aaron Green"],
      director: "Flora Belle",
      type: "Movie"
    },
    {
      id: "LEAF-w2c6",
      title: "Leaf Chronicles",
      description: "Nature’s poetry in motion across the changing seasons.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909369/stream/video/06LeafVideo/06LeafThumb_foobm8.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909209/stream/video/06LeafVideo/06LeafVideo_mmpoky.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909209/stream/video/06LeafVideo/06LeafVideo_mmpoky.mp4",
      rating: 4.4,
      date: "2022",
      plot: "A tiny leaf embarks on an epic adventure from towering forests to bustling city streets.",
      genre: ["Animation", "Adventure", "Family"],
      language: "English",
      duration: "1h 20m",
      cast: ["Voice of Max Greenleaf"],
      director: "Wendy Woods",
      type: "Movie"
    },
    {
      id: "PYRA-q1m4",
      title: "Pyramid Secrets",
      description: "Unlock the mysteries buried deep beneath ancient sands.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909393/stream/video/07PyrmdVideo/07PyrmdThumb_ns0els.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909082/stream/video/07PyrmdVideo/07PyrmdVideo_wejjqd.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909082/stream/video/07PyrmdVideo/07PyrmdVideo_wejjqd.mp4",
      rating: 4.8,
      date: "2023",
      plot: "Archaeologists uncover hidden chambers and forgotten treasures inside the greatest pyramids ever built.",
      genre: ["Documentary", "History", "Mystery"],
      language: "English",
      duration: "1h 50m",
      cast: ["Narrated by Morgan Graves"],
      director: "Leon Sands",
      type: "Documentary"
    },
    {
      id: "WATE-a7n5",
      title: "City of Water",
      description: "A surreal future where dreams float and cities breathe underwater.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909413/stream/video/08WaterCityVideo/08WaterCityThumb_ba9emc.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909093/stream/video/08WaterCityVideo/08WaterCityVideo_e0dsag.mp4",
      fullVideo: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909093/stream/video/08WaterCityVideo/08WaterCityVideo_e0dsag.mp4",
      rating: 4.2,
      date: "2021",
      plot: "A breathtaking story of hope, architecture, and humanity’s survival beneath the seas.",
      genre: ["Sci-Fi", "Drama"],
      language: "English",
      duration: "2h 5m",
      cast: ["Marina Blue", "Caspian Wells"],
      director: "Aqua Lune",
      type: "Movie"
    },
    {
      id: "WATE-z6p8",
      title: "Waves of Time",
      description: "Ancient rivers and waterfalls carve the story of civilization.",
      thumbnail: "https://res.cloudinary.com/de6u5kbiw/image/upload/v1745909435/stream/video/09WaterVideo/09WaterThumb_afxj7k.png",
      video: "https://res.cloudinary.com/de6u5kbiw/video/upload/v1745909135/stream/video/09WaterVideo/09WaterVideo_q9mojn.mp4",
      fullVideo: "",
      rating: 4.5,
      date: "2020",
      plot: "From ancient waterfalls to hidden river cities, explore how water shaped humanity’s greatest triumphs.",
      genre: ["Documentary", "Travel", "History"],
      language: "English",
      duration: "1h 15m",
      cast: ["Narrated by Oliver Brooks"],
      director: "Isla Cascade",
      type: "Documentary"
    },
  ];


  // const ads = [
  //   {
  //     id: "barAds-001",
  //     title: "Bar Ad",
  //     description: "A promotional ad for a trendy bar, showcasing its ambiance and drinks.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/barAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "cakeAds-001",
  //     title: "Cake Ad",
  //     description: "An ad promoting delicious cakes from a local bakery, perfect for all occasions.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/cakeAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "donutsAds-001",
  //     title: "Donuts Ad",
  //     description: "An ad for a donut shop offering a variety of fresh donuts, perfect for your sweet cravings.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donatsAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donutads.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/donutads.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "friesAds-001",
  //     title: "Fries Ad",
  //     description: "A crispy, golden fries ad for a fast-food chain, perfect for your snacking moments.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/friesAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "gymAds-001",
  //     title: "Gym Ad",
  //     description: "An ad for a fitness gym offering special discounts for new memberships.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/gymAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "hairAds-001",
  //     title: "Hair Products Ad",
  //     description: "An ad for a hair care product that promises to give you healthy, shiny hair.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/hairAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
    // {
    //   id: "restaurantAds-001",
    //   title: "Restaurant Ad",
    //   description: "A mouth-watering ad for a local restaurant offering a special discount on meals.",
    //   thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.png",
    //   video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.mp4",
    //   fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/resturantAds.mp4",
    //   rating: "n/a",
    //   date: "n/a",
    //   plot: "n/a",
    //   genre: ["n/a"],
    //   language: "n/a",
    //   duration: "n/a",
    //   cast: ["n/a"],
    //   director: "n/a",
    //   type: "AD"
    // },
  //   {
  //     id: "spaAds-001",
  //     title: "Spa Ad",
  //     description: "A relaxing ad promoting a luxury spa experience, perfect for rejuvenating your body and mind.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/spaAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/spaAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/spaAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   },
  //   {
  //     id: "storeAds-001",
  //     title: "Store Ad",
  //     description: "An ad for an online store offering discounts on various products.",
  //     thumbnail: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/storeAds.png",
  //     video: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/storeAds.mp4",
  //     fullVideo: "https://storage.googleapis.com/1000gns/1001/content/ads/Refined%20Ads/storeAds.mp4",
  //     rating: "n/a",
  //     date: "n/a",
  //     plot: "n/a",
  //     genre: ["n/a"],
  //     language: "n/a",
  //     duration: "n/a",
  //     cast: ["n/a"],
  //     director: "n/a",
  //     type: "AD"
  //   }
  // ];
  